use crate::{Error, ir::Module};
use std::ffi::{CStr, CString};
use std::marker::PhantomData;

// ---------------------------------------------------------------------------
// Raw FFI declarations for LLVM ORC / LLJIT C API
//
// These are declared manually rather than generated by bindgen so that
// mlir-sys does not need to pull in all of llvm-c/Core.h.  The symbols are
// already linked via mlir-sys's llvm-config integration.
// ---------------------------------------------------------------------------

#[allow(non_camel_case_types, dead_code)]
mod ffi {
    use std::ffi::c_char;

    // Opaque pointer types -------------------------------------------------

    pub type LLVMOrcLLJITBuilderRef = *mut std::ffi::c_void;
    pub type LLVMOrcLLJITRef = *mut std::ffi::c_void;
    pub type LLVMOrcExecutionSessionRef = *mut std::ffi::c_void;
    pub type LLVMOrcJITDylibRef = *mut std::ffi::c_void;
    pub type LLVMOrcThreadSafeContextRef = *mut std::ffi::c_void;
    pub type LLVMOrcThreadSafeModuleRef = *mut std::ffi::c_void;
    pub type LLVMOrcSymbolStringPoolEntryRef = *mut std::ffi::c_void;
    pub type LLVMOrcMaterializationUnitRef = *mut std::ffi::c_void;
    pub type LLVMOrcDefinitionGeneratorRef = *mut std::ffi::c_void;
    pub type LLVMErrorRef = *mut std::ffi::c_void;
    pub type LLVMContextRef = *mut std::ffi::c_void;
    pub type LLVMModuleRef = *mut std::ffi::c_void;

    // Value types -----------------------------------------------------------

    pub type LLVMOrcExecutorAddress = u64;

    #[repr(C)]
    pub struct LLVMJITSymbolFlags {
        pub generic_flags: u8,
        pub target_flags: u8,
    }

    #[repr(C)]
    pub struct LLVMJITEvaluatedSymbol {
        pub address: LLVMOrcExecutorAddress,
        pub flags: LLVMJITSymbolFlags,
    }

    #[repr(C)]
    pub struct LLVMOrcCSymbolMapPair {
        pub name: LLVMOrcSymbolStringPoolEntryRef,
        pub sym: LLVMJITEvaluatedSymbol,
    }

    pub type LLVMOrcCSymbolMapPairs = *mut LLVMOrcCSymbolMapPair;

    // Definition generator callback types

    pub type LLVMOrcCLookupSet = *const LLVMOrcCLookupSetElement;

    #[repr(C)]
    pub struct LLVMOrcCLookupSetElement {
        pub name: LLVMOrcSymbolStringPoolEntryRef,
        pub lookup_flags: u32,
    }

    pub type LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction = unsafe extern "C" fn(
        generator_obj: LLVMOrcDefinitionGeneratorRef,
        ctx: *mut std::ffi::c_void,
        lookup_state: *mut *mut std::ffi::c_void,
        kind: u32,
        jd: LLVMOrcJITDylibRef,
        jd_lookup_flags: u32,
        lookup_set: LLVMOrcCLookupSet,
        lookup_set_size: usize,
    ) -> LLVMErrorRef;

    // Functions -------------------------------------------------------------

    unsafe extern "C" {
        // LLVM Context
        pub fn LLVMContextCreate() -> LLVMContextRef;
        pub fn LLVMContextDispose(c: LLVMContextRef);

        // LLVM Error
        pub fn LLVMGetErrorMessage(err: LLVMErrorRef) -> *mut c_char;
        pub fn LLVMDisposeErrorMessage(msg: *mut c_char);

        // MLIR → LLVM IR translation
        pub fn mlirTranslateModuleToLLVMIR(
            module: mlir_sys::MlirOperation,
            context: LLVMContextRef,
        ) -> LLVMModuleRef;

        // LLJIT lifecycle
        pub fn LLVMOrcCreateLLJITBuilder() -> LLVMOrcLLJITBuilderRef;
        pub fn LLVMOrcCreateLLJIT(
            result: *mut LLVMOrcLLJITRef,
            builder: LLVMOrcLLJITBuilderRef,
        ) -> LLVMErrorRef;
        pub fn LLVMOrcDisposeLLJIT(j: LLVMOrcLLJITRef) -> LLVMErrorRef;

        // LLJIT accessors
        pub fn LLVMOrcLLJITGetExecutionSession(j: LLVMOrcLLJITRef) -> LLVMOrcExecutionSessionRef;
        pub fn LLVMOrcLLJITGetMainJITDylib(j: LLVMOrcLLJITRef) -> LLVMOrcJITDylibRef;
        pub fn LLVMOrcLLJITGetGlobalPrefix(j: LLVMOrcLLJITRef) -> c_char;

        // Module addition
        pub fn LLVMOrcLLJITAddLLVMIRModule(
            j: LLVMOrcLLJITRef,
            jd: LLVMOrcJITDylibRef,
            tsm: LLVMOrcThreadSafeModuleRef,
        ) -> LLVMErrorRef;

        // Symbol lookup
        pub fn LLVMOrcLLJITLookup(
            j: LLVMOrcLLJITRef,
            result: *mut LLVMOrcExecutorAddress,
            name: *const c_char,
        ) -> LLVMErrorRef;

        // Mangle + intern
        pub fn LLVMOrcLLJITMangleAndIntern(
            j: LLVMOrcLLJITRef,
            unmangled_name: *const c_char,
        ) -> LLVMOrcSymbolStringPoolEntryRef;

        // JITDylib creation
        pub fn LLVMOrcExecutionSessionCreateJITDylib(
            es: LLVMOrcExecutionSessionRef,
            result: *mut LLVMOrcJITDylibRef,
            name: *const c_char,
        ) -> LLVMErrorRef;

        // Symbol definition
        pub fn LLVMOrcJITDylibDefine(
            jd: LLVMOrcJITDylibRef,
            mu: LLVMOrcMaterializationUnitRef,
        ) -> LLVMErrorRef;

        pub fn LLVMOrcAbsoluteSymbols(
            syms: LLVMOrcCSymbolMapPairs,
            num_pairs: usize,
        ) -> LLVMOrcMaterializationUnitRef;

        pub fn LLVMOrcDisposeMaterializationUnit(mu: LLVMOrcMaterializationUnitRef);

        // Symbol string pool
        pub fn LLVMOrcExecutionSessionIntern(
            es: LLVMOrcExecutionSessionRef,
            name: *const c_char,
        ) -> LLVMOrcSymbolStringPoolEntryRef;

        pub fn LLVMOrcReleaseSymbolStringPoolEntry(s: LLVMOrcSymbolStringPoolEntryRef);

        // Definition generator
        pub fn LLVMOrcCreateCustomCAPIDefinitionGenerator(
            f: LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction,
            ctx: *mut std::ffi::c_void,
            dispose: Option<unsafe extern "C" fn(*mut std::ffi::c_void)>,
        ) -> LLVMOrcDefinitionGeneratorRef;

        pub fn LLVMOrcJITDylibAddGenerator(
            jd: LLVMOrcJITDylibRef,
            dg: LLVMOrcDefinitionGeneratorRef,
        );

        pub fn LLVMOrcSymbolStringPoolEntryStr(
            entry: LLVMOrcSymbolStringPoolEntryRef,
        ) -> *const c_char;

        // Thread-safe context and module
        pub fn LLVMOrcCreateNewThreadSafeContext() -> LLVMOrcThreadSafeContextRef;
        pub fn LLVMOrcDisposeThreadSafeContext(tsc: LLVMOrcThreadSafeContextRef);

        pub fn LLVMOrcCreateNewThreadSafeModule(
            m: LLVMModuleRef,
            tsc: LLVMOrcThreadSafeContextRef,
        ) -> LLVMOrcThreadSafeModuleRef;
        pub fn LLVMOrcDisposeThreadSafeModule(tsm: LLVMOrcThreadSafeModuleRef);

        // LLVM module disposal (needed if translation fails before wrapping)
        pub fn LLVMDisposeModule(m: LLVMModuleRef);

        // LLVM target initialization (per-platform symbols)
        #[cfg(target_arch = "aarch64")]
        pub fn LLVMInitializeAArch64TargetInfo();
        #[cfg(target_arch = "aarch64")]
        pub fn LLVMInitializeAArch64Target();
        #[cfg(target_arch = "aarch64")]
        pub fn LLVMInitializeAArch64TargetMC();
        #[cfg(target_arch = "aarch64")]
        pub fn LLVMInitializeAArch64AsmPrinter();

        #[cfg(target_arch = "x86_64")]
        pub fn LLVMInitializeX86TargetInfo();
        #[cfg(target_arch = "x86_64")]
        pub fn LLVMInitializeX86Target();
        #[cfg(target_arch = "x86_64")]
        pub fn LLVMInitializeX86TargetMC();
        #[cfg(target_arch = "x86_64")]
        pub fn LLVMInitializeX86AsmPrinter();
    }

    /// Initialize the native target for JIT compilation.
    /// Must be called before creating an LLJIT instance.
    pub fn initialize_native_target() {
        unsafe {
            #[cfg(target_arch = "aarch64")]
            {
                LLVMInitializeAArch64TargetInfo();
                LLVMInitializeAArch64Target();
                LLVMInitializeAArch64TargetMC();
                LLVMInitializeAArch64AsmPrinter();
            }
            #[cfg(target_arch = "x86_64")]
            {
                LLVMInitializeX86TargetInfo();
                LLVMInitializeX86Target();
                LLVMInitializeX86TargetMC();
                LLVMInitializeX86AsmPrinter();
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Error conversion
// ---------------------------------------------------------------------------

fn llvm_error_to_string(err: ffi::LLVMErrorRef) -> String {
    if err.is_null() {
        return String::new();
    }
    unsafe {
        let msg = ffi::LLVMGetErrorMessage(err);
        let result = CStr::from_ptr(msg).to_string_lossy().into_owned();
        ffi::LLVMDisposeErrorMessage(msg);
        result
    }
}

fn check_llvm_error(err: ffi::LLVMErrorRef) -> Result<(), Error> {
    if err.is_null() {
        Ok(())
    } else {
        Err(Error::Lljit(llvm_error_to_string(err)))
    }
}

// ---------------------------------------------------------------------------
// Safe wrappers
// ---------------------------------------------------------------------------

/// A JITDylib reference. Borrowed from the owning `Lljit`.
///
/// JITDylibs are symbol namespaces. Modules added to a JITDylib define
/// symbols in that namespace. Symbol lookup searches JITDylibs.
#[derive(Clone, Copy)]
pub struct JitDylib<'jit> {
    raw: ffi::LLVMOrcJITDylibRef,
    _marker: PhantomData<&'jit Lljit>,
}

/// A thread-safe LLVM IR module ready to be added to an `Lljit`.
///
/// Created from an MLIR module via `ThreadSafeModule::from_mlir`. Consumed
/// by `Lljit::add_module`.
pub struct ThreadSafeModule {
    raw: ffi::LLVMOrcThreadSafeModuleRef,
}

impl ThreadSafeModule {
    /// Translate an MLIR module to LLVM IR and wrap it for the JIT.
    ///
    /// This performs the full MLIR → LLVM IR translation. The resulting
    /// module is ready to be passed to `Lljit::add_module`.
    pub fn from_mlir(module: &Module) -> Result<Self, Error> {
        unsafe {
            let ts_ctx = ffi::LLVMOrcCreateNewThreadSafeContext();
            if ts_ctx.is_null() {
                return Err(Error::Lljit(
                    "failed to create thread-safe context".to_string(),
                ));
            }

            // mlirTranslateModuleToLLVMIR needs a bare LLVMContext.
            let llvm_ctx = ffi::LLVMContextCreate();
            if llvm_ctx.is_null() {
                ffi::LLVMOrcDisposeThreadSafeContext(ts_ctx);
                return Err(Error::Lljit("failed to create LLVM context".to_string()));
            }

            let llvm_module = ffi::mlirTranslateModuleToLLVMIR(
                module.as_operation().to_raw(),
                llvm_ctx,
            );

            if llvm_module.is_null() {
                ffi::LLVMContextDispose(llvm_ctx);
                ffi::LLVMOrcDisposeThreadSafeContext(ts_ctx);
                return Err(Error::Lljit(
                    "failed to translate MLIR module to LLVM IR".to_string(),
                ));
            }

            // mlirTranslateModuleToLLVMIR requires a bare LLVMContext, but
            // LLVMOrcCreateNewThreadSafeModule needs a ThreadSafeContext that
            // wraps the same LLVMContext. We translate first, then wrap the
            // translation context via LLVMOrcCreateNewThreadSafeContextFromLLVMContext.
            ffi::LLVMOrcDisposeThreadSafeContext(ts_ctx);

            let ts_ctx = LLVMOrcCreateNewThreadSafeContextFromLLVMContext(llvm_ctx);
            let tsm = ffi::LLVMOrcCreateNewThreadSafeModule(llvm_module, ts_ctx);
            // TSM now owns the module. TSCtx is shared (ref-counted).
            ffi::LLVMOrcDisposeThreadSafeContext(ts_ctx);

            if tsm.is_null() {
                return Err(Error::Lljit(
                    "failed to create thread-safe module".to_string(),
                ));
            }

            Ok(Self { raw: tsm })
        }
    }
}

impl Drop for ThreadSafeModule {
    fn drop(&mut self) {
        if !self.raw.is_null() {
            unsafe { ffi::LLVMOrcDisposeThreadSafeModule(self.raw) }
        }
    }
}

// Additional FFI declarations not in the main ffi block.
unsafe extern "C" {
    fn LLVMOrcCreateNewThreadSafeContextFromLLVMContext(
        ctx: ffi::LLVMContextRef,
    ) -> ffi::LLVMOrcThreadSafeContextRef;

    fn LLVMCreateStringError(msg: *const std::ffi::c_char) -> ffi::LLVMErrorRef;
}

fn llvm_create_string_error(msg: *const std::ffi::c_char) -> ffi::LLVMErrorRef {
    unsafe { LLVMCreateStringError(msg) }
}


/// LLVM's LLJIT: an incremental JIT compiler.
///
/// Supports adding multiple LLVM IR modules over time, with cross-module
/// symbol resolution. Each module's symbols are available to subsequently
/// added modules and to `lookup` queries.
pub struct Lljit {
    raw: ffi::LLVMOrcLLJITRef,
}

impl Lljit {
    /// Create a new LLJIT instance with default configuration.
    ///
    /// Initializes the native LLVM target on first call. This is required
    /// for LLJIT to find the host target triple and generate code.
    pub fn new() -> Result<Self, Error> {
        use std::sync::Once;
        static INIT: Once = Once::new();
        INIT.call_once(ffi::initialize_native_target);

        unsafe {
            let builder = ffi::LLVMOrcCreateLLJITBuilder();
            let mut raw = std::ptr::null_mut();
            let err = ffi::LLVMOrcCreateLLJIT(&mut raw, builder);
            check_llvm_error(err)?;

            Ok(Self { raw })
        }
    }

    /// Get the main JITDylib. All modules are added here by default.
    pub fn main_dylib(&self) -> JitDylib<'_> {
        JitDylib {
            raw: unsafe { ffi::LLVMOrcLLJITGetMainJITDylib(self.raw) },
            _marker: PhantomData,
        }
    }

    /// Create a new JITDylib with the given name.
    ///
    /// The name must be unique within this LLJIT instance.
    pub fn create_dylib(&self, name: &str) -> Result<JitDylib<'_>, Error> {
        let c_name = CString::new(name).map_err(|_| {
            Error::Lljit(format!("JITDylib name contains null byte: {name}"))
        })?;

        unsafe {
            let es = ffi::LLVMOrcLLJITGetExecutionSession(self.raw);
            let mut raw = std::ptr::null_mut();
            let err = ffi::LLVMOrcExecutionSessionCreateJITDylib(es, &mut raw, c_name.as_ptr());
            check_llvm_error(err)?;

            Ok(JitDylib {
                raw,
                _marker: PhantomData,
            })
        }
    }

    /// Add an LLVM IR module to a JITDylib.
    ///
    /// This takes ownership of the module. Symbols defined in the module
    /// become available for lookup and cross-module references.
    pub fn add_module(&self, dylib: &JitDylib<'_>, module: ThreadSafeModule) -> Result<(), Error> {
        let raw_tsm = module.raw;
        std::mem::forget(module); // LLJIT takes ownership; don't drop

        unsafe {
            let err = ffi::LLVMOrcLLJITAddLLVMIRModule(self.raw, dylib.raw, raw_tsm);
            check_llvm_error(err)
        }
    }

    /// Look up a symbol by name. Returns the address of the symbol.
    ///
    /// The name is automatically mangled according to the target's data
    /// layout (e.g., prefixed with `_` on macOS).
    pub fn lookup(&self, name: &str) -> Result<u64, Error> {
        let c_name = CString::new(name).map_err(|_| {
            Error::Lljit(format!("symbol name contains null byte: {name}"))
        })?;

        unsafe {
            let mut addr: ffi::LLVMOrcExecutorAddress = 0;
            let err = ffi::LLVMOrcLLJITLookup(self.raw, &mut addr, c_name.as_ptr());
            check_llvm_error(err)?;
            Ok(addr)
        }
    }

    /// Register absolute symbols (e.g., host function pointers) in a JITDylib.
    ///
    /// Each entry is a `(name, address)` pair. The symbols are registered as
    /// exported with callable flags, suitable for registering runtime functions.
    pub fn define_absolute_symbols(
        &self,
        dylib: &JitDylib<'_>,
        symbols: &[(&str, u64)],
    ) -> Result<(), Error> {
        if symbols.is_empty() {
            return Ok(());
        }

        unsafe {
            let mut pairs: Vec<ffi::LLVMOrcCSymbolMapPair> = Vec::with_capacity(symbols.len());
            let mut interned_names: Vec<ffi::LLVMOrcSymbolStringPoolEntryRef> =
                Vec::with_capacity(symbols.len());

            for &(name, addr) in symbols {
                let c_name = CString::new(name).map_err(|_| {
                    Error::Lljit(format!("symbol name contains null byte: {name}"))
                })?;
                let interned = ffi::LLVMOrcLLJITMangleAndIntern(self.raw, c_name.as_ptr());
                interned_names.push(interned);

                pairs.push(ffi::LLVMOrcCSymbolMapPair {
                    name: interned,
                    sym: ffi::LLVMJITEvaluatedSymbol {
                        address: addr,
                        flags: ffi::LLVMJITSymbolFlags {
                            // Exported | Callable
                            generic_flags: (1 << 0) | (1 << 2),
                            target_flags: 0,
                        },
                    },
                });
            }

            let mu = ffi::LLVMOrcAbsoluteSymbols(pairs.as_mut_ptr(), pairs.len());

            let err = ffi::LLVMOrcJITDylibDefine(dylib.raw, mu);
            if !err.is_null() {
                // On failure, we own the MU and must dispose it.
                // But LLVMOrcJITDylibDefine consumes it on success.
                // The error path documentation says caller must dispose MU on failure,
                // but since we passed it to Define, LLVM may have consumed it.
                // In practice, LLVMOrcJITDylibDefine takes ownership even on error
                // in some LLVM versions. To be safe, we just propagate the error.
                for entry in &interned_names {
                    ffi::LLVMOrcReleaseSymbolStringPoolEntry(*entry);
                }
                return Err(Error::Lljit(llvm_error_to_string(err)));
            }

            // On success, the JITDylib owns the interned names via the MU.
            // We still need to release our ref-count on the interned entries.
            for entry in &interned_names {
                ffi::LLVMOrcReleaseSymbolStringPoolEntry(*entry);
            }

            Ok(())
        }
    }

    /// Get the global prefix character for this target (e.g. '_' on macOS).
    pub fn global_prefix(&self) -> char {
        unsafe { ffi::LLVMOrcLLJITGetGlobalPrefix(self.raw) as u8 as char }
    }

    /// Register a definition generator on a JITDylib.
    ///
    /// When the JIT encounters an undefined symbol during lookup or execution,
    /// ORC invokes this callback with the symbol name. The callback can compile
    /// and add a module containing the symbol, return `Ok(None)` to pass, or
    /// return `Err` to abort.
    ///
    /// The callback receives the raw (mangled) symbol name. On macOS this
    /// includes the `_` prefix. Use `global_prefix()` to strip it.
    pub fn add_definition_generator<F>(&self, dylib: &JitDylib<'_>, callback: F)
    where
        F: Fn(&str, &Lljit, &JitDylib<'_>) -> Result<bool, Error> + 'static,
    {
        struct GeneratorCtx<F> {
            callback: F,
            jit_raw: ffi::LLVMOrcLLJITRef,
        }

        unsafe extern "C" fn trampoline<F>(
            _generator_obj: ffi::LLVMOrcDefinitionGeneratorRef,
            user_ctx: *mut std::ffi::c_void,
            _lookup_state: *mut *mut std::ffi::c_void,
            _kind: u32,
            jd: ffi::LLVMOrcJITDylibRef,
            _jd_lookup_flags: u32,
            lookup_set: ffi::LLVMOrcCLookupSet,
            lookup_set_size: usize,
        ) -> ffi::LLVMErrorRef
        where
            F: Fn(&str, &Lljit, &JitDylib<'_>) -> Result<bool, Error> + 'static,
        {
            unsafe {
                let ctx = &*(user_ctx as *const GeneratorCtx<F>);
                let jit = Lljit { raw: ctx.jit_raw };
                let dylib = JitDylib {
                    raw: jd,
                    _marker: PhantomData,
                };

                for i in 0..lookup_set_size {
                    let element = &*lookup_set.add(i);
                    let c_str = ffi::LLVMOrcSymbolStringPoolEntryStr(element.name);
                    let name = match CStr::from_ptr(c_str).to_str() {
                        Ok(s) => s,
                        Err(_) => continue,
                    };

                    match (ctx.callback)(name, &jit, &dylib) {
                        Ok(_) => {}
                        Err(e) => {
                            std::mem::forget(jit);
                            let msg = CString::new(format!("{e}")).unwrap_or_default();
                            return llvm_create_string_error(msg.as_ptr());
                        }
                    }
                }

                std::mem::forget(jit);
                std::ptr::null_mut()
            }
        }

        unsafe extern "C" fn dispose<F>(ctx: *mut std::ffi::c_void) {
            unsafe { drop(Box::from_raw(ctx as *mut GeneratorCtx<F>)); }
        }

        let ctx = Box::new(GeneratorCtx {
            callback,
            jit_raw: self.raw,
        });
        let ctx_ptr = Box::into_raw(ctx) as *mut std::ffi::c_void;

        unsafe {
            let def_gen = ffi::LLVMOrcCreateCustomCAPIDefinitionGenerator(
                trampoline::<F>,
                ctx_ptr,
                Some(dispose::<F>),
            );
            ffi::LLVMOrcJITDylibAddGenerator(dylib.raw, def_gen);
        }
    }
}

impl Drop for Lljit {
    fn drop(&mut self) {
        if !self.raw.is_null() {
            unsafe {
                let err = ffi::LLVMOrcDisposeLLJIT(self.raw);
                if !err.is_null() {
                    // Best effort: log but don't panic in Drop
                    let msg = llvm_error_to_string(err);
                    eprintln!("warning: error disposing LLJIT: {msg}");
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{pass, test::create_test_context};

    #[test]
    fn create_and_drop() {
        let jit = Lljit::new().expect("failed to create LLJIT");
        drop(jit);
    }

    #[test]
    fn main_dylib() {
        let jit = Lljit::new().expect("failed to create LLJIT");
        let _dylib = jit.main_dylib();
    }

    #[test]
    fn create_dylib() {
        let jit = Lljit::new().expect("failed to create LLJIT");
        let _dylib = jit.create_dylib("test_lib").expect("failed to create JITDylib");
    }

    #[test]
    fn global_prefix() {
        let jit = Lljit::new().expect("failed to create LLJIT");
        let prefix = jit.global_prefix();
        // On macOS the prefix is '_', on Linux it's '\0' (no prefix)
        assert!(prefix == '_' || prefix == '\0');
    }

    #[test]
    fn add_module_and_lookup() {
        let context = create_test_context();

        let mut module = Module::parse(
            &context,
            r#"
            module {
                func.func @add(%arg0 : i32, %arg1 : i32) -> i32 {
                    %res = arith.addi %arg0, %arg1 : i32
                    return %res : i32
                }
            }
            "#,
        )
        .unwrap();

        let pass_manager = pass::PassManager::new(&context);
        pass_manager.add_pass(pass::conversion::create_to_llvm());
        pass_manager.run(&mut module).expect("pass pipeline failed");

        let tsm = ThreadSafeModule::from_mlir(&module).expect("MLIR→LLVM translation failed");

        let jit = Lljit::new().expect("failed to create LLJIT");
        let dylib = jit.main_dylib();
        jit.add_module(&dylib, tsm).expect("failed to add module");

        let addr = jit.lookup("add").expect("failed to look up 'add'");
        assert_ne!(addr, 0, "symbol address should not be zero");

        let add_fn: extern "C" fn(i32, i32) -> i32 = unsafe { std::mem::transmute(addr) };
        assert_eq!(add_fn(21, 21), 42);
    }

    #[test]
    fn define_absolute_symbols_and_call() {
        extern "C" fn host_multiply(a: i64, b: i64) -> i64 {
            a * b
        }

        let context = create_test_context();

        let mut module = Module::parse(
            &context,
            r#"
            module {
                func.func private @host_multiply(i64, i64) -> i64

                func.func @call_host(%a : i64, %b : i64) -> i64 {
                    %res = func.call @host_multiply(%a, %b) : (i64, i64) -> i64
                    return %res : i64
                }
            }
            "#,
        )
        .unwrap();

        let pass_manager = pass::PassManager::new(&context);
        pass_manager.add_pass(pass::conversion::create_to_llvm());
        pass_manager.run(&mut module).expect("pass pipeline failed");

        let tsm = ThreadSafeModule::from_mlir(&module).expect("MLIR→LLVM translation failed");

        let jit = Lljit::new().expect("failed to create LLJIT");
        let dylib = jit.main_dylib();

        jit.define_absolute_symbols(
            &dylib,
            &[("host_multiply", host_multiply as u64)],
        )
        .expect("failed to define symbols");

        jit.add_module(&dylib, tsm).expect("failed to add module");

        let addr = jit.lookup("call_host").expect("failed to look up 'call_host'");
        let call_host: extern "C" fn(i64, i64) -> i64 = unsafe { std::mem::transmute(addr) };
        assert_eq!(call_host(6, 7), 42);
    }

    #[test]
    fn definition_generator_lazy_compile() {
        use std::sync::{Arc, Mutex};

        let context = create_test_context();

        // Pre-compile the lazy module so the generator just hands it over.
        let mut square_mod = Module::parse(
            &context,
            r#"
            module {
                func.func @square(%x : i64) -> i64 {
                    %res = arith.muli %x, %x : i64
                    return %res : i64
                }
            }
            "#,
        )
        .unwrap();

        let pm = pass::PassManager::new(&context);
        pm.add_pass(pass::conversion::create_to_llvm());
        pm.run(&mut square_mod).expect("pass pipeline failed");

        let tsm_holder: Arc<Mutex<Option<ThreadSafeModule>>> = Arc::new(Mutex::new(
            Some(ThreadSafeModule::from_mlir(&square_mod).expect("translation failed")),
        ));

        // Module that calls @square but doesn't define it.
        let mut caller_module = Module::parse(
            &context,
            r#"
            module {
                func.func private @square(i64) -> i64

                func.func @use_square(%x : i64) -> i64 {
                    %res = func.call @square(%x) : (i64) -> i64
                    return %res : i64
                }
            }
            "#,
        )
        .unwrap();

        let pm2 = pass::PassManager::new(&context);
        pm2.add_pass(pass::conversion::create_to_llvm());
        pm2.run(&mut caller_module).expect("pass pipeline failed");

        let jit = Lljit::new().expect("failed to create LLJIT");
        let dylib = jit.main_dylib();

        let holder_clone = tsm_holder.clone();
        jit.add_definition_generator(&dylib, move |name, jit, dylib| {
            let prefix = jit.global_prefix();
            let bare = if prefix != '\0' {
                name.strip_prefix(prefix).unwrap_or(name)
            } else {
                name
            };

            if bare != "square" {
                return Ok(false);
            }

            let tsm = holder_clone.lock().unwrap().take()
                .ok_or_else(|| Error::Lljit("square already provided".to_string()))?;
            jit.add_module(dylib, tsm)?;
            Ok(true)
        });

        let caller_tsm = ThreadSafeModule::from_mlir(&caller_module)
            .expect("MLIR→LLVM translation failed");
        jit.add_module(&dylib, caller_tsm).expect("failed to add caller module");

        let addr = jit.lookup("use_square").expect("failed to look up use_square");
        let use_square: extern "C" fn(i64) -> i64 = unsafe { std::mem::transmute(addr) };
        assert_eq!(use_square(7), 49);
    }

    #[test]
    fn incremental_modules() {
        let context = create_test_context();

        // Module 1: define a function
        let mut module1 = Module::parse(
            &context,
            r#"
            module {
                func.func @square(%x : i64) -> i64 {
                    %res = arith.muli %x, %x : i64
                    return %res : i64
                }
            }
            "#,
        )
        .unwrap();

        let pass_manager = pass::PassManager::new(&context);
        pass_manager.add_pass(pass::conversion::create_to_llvm());
        pass_manager.run(&mut module1).expect("pass pipeline failed");

        // Module 2: call the function from module 1
        let mut module2 = Module::parse(
            &context,
            r#"
            module {
                func.func private @square(i64) -> i64

                func.func @square_plus_one(%x : i64) -> i64 {
                    %sq = func.call @square(%x) : (i64) -> i64
                    %one = arith.constant 1 : i64
                    %res = arith.addi %sq, %one : i64
                    return %res : i64
                }
            }
            "#,
        )
        .unwrap();

        let pass_manager2 = pass::PassManager::new(&context);
        pass_manager2.add_pass(pass::conversion::create_to_llvm());
        pass_manager2.run(&mut module2).expect("pass pipeline failed");

        let jit = Lljit::new().expect("failed to create LLJIT");
        let dylib = jit.main_dylib();

        let tsm1 = ThreadSafeModule::from_mlir(&module1).expect("translation failed");
        jit.add_module(&dylib, tsm1).expect("failed to add module 1");

        let tsm2 = ThreadSafeModule::from_mlir(&module2).expect("translation failed");
        jit.add_module(&dylib, tsm2).expect("failed to add module 2");

        let addr = jit.lookup("square_plus_one").expect("lookup failed");
        let square_plus_one: extern "C" fn(i64) -> i64 = unsafe { std::mem::transmute(addr) };
        assert_eq!(square_plus_one(5), 26); // 5*5 + 1 = 26
    }
}
